### PR TITLE
Initial set of patches which add RPi5 support

### PR DESCRIPTION
**Pull request by hanzyd**
With these patches I am able to _start_ current openSUSE
Tumbleweed without modification. They are still a lot of
things to be added to the upstream Linux
before it runs flawlessly on this device, but at
least in U-Booot SD controller used for uSD card
and Frameboffer and HDMI0 devices are working fine
now. It seems that PCIe controller is working fine
too, but I have not tested it too much.

Serial console and reset are also functional.

### CODE REVIEW

**Comment by mauromorales** [comment]
@mbgg I'm not sure how the release process from this package and Tumbleweed works, being merged does it mean that it was already released in Jan 2024 Tumbleweed?

**Comment by hanzyd** [comment]
It is for sure part of the current Tumbleweed :-)

**Comment by mauromorales** [comment]
@hanzyd awesome thanks! And does that mean that Tumbleweed runs on rpi5? or is there something still missing for that to work out of the box? I've been trying on my end, but I'm not sure if the images I'm building are flawed or if it's just not ready yet

**Comment by hanzyd** [comment]
Tumbleweed runs on more or less current Linux master branch, so whatever support Linux gained it is in Tumbleweed.  On a practical side this means, at the moment, it boots to serial console prompt. They are few WIP patch sets which is going to add support for PCIe, RP1 (USB ....), WiFi and BT.

**Comment by mauromorales** [comment]
@hanzyd fantastic, thanks for the clarification

**Pull request merged**
