### PR TITLE
Use OF_CONTROL on bcm283x

### PR DESCRIPTION
**Pull request by Vogtinator**
Somehow I got this message multiple times during booting, but it appears with the older DTB as well:

```
vc4-drm soc:gpu: failed to bind 3f902000.hdmi (ops vc4_hdmi_ops [vc4]): -517
```

### CODE REVIEW

**Comment by Vogtinator** [comment]
The message doesn't appear with a different rootfs though, so it's likely unrelated to these patches.

**Comment by dirkmueller** [comment]
+1

**Comment by afaerber** [comment]
This has folded all patches into one huge commit! Please don't do that.

**Comment by dirkmueller** [comment]
should be fixed now

**Comment by afaerber** [comment]
Reverted these for now on tumbleweed branch

**Comment by Vogtinator** [comment]
There has to be a way to maintain the u-boot packages in SP2/42.2, maybe a new branch is the best option?

**Comment by afaerber** [comment]
For now pushed as fvogt-2016.07

**Pull request merged**
